// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPa1l3cj_hUkCZyjLXOQBmpUrNCmmhKpI',
    appId: '1:19239814105:web:0c288e2258d553f1810fc8',
    messagingSenderId: '19239814105',
    projectId: 'test-d994f',
    authDomain: 'test-d994f.firebaseapp.com',
    storageBucket: 'test-d994f.appspot.com',
    measurementId: 'G-VN9KVZTRY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYOFYaEEPQcnICEVc4Jxiw3uHXRoc3_LQ',
    appId: '1:19239814105:android:007d9b73c5bba5d5810fc8',
    messagingSenderId: '19239814105',
    projectId: 'test-d994f',
    storageBucket: 'test-d994f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyMR_d2pduquyBmhjc8uZU775DrQ0JKnU',
    appId: '1:19239814105:ios:8489eb43f6dc8520810fc8',
    messagingSenderId: '19239814105',
    projectId: 'test-d994f',
    storageBucket: 'test-d994f.appspot.com',
    iosBundleId: 'com.example.Lucerna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyMR_d2pduquyBmhjc8uZU775DrQ0JKnU',
    appId: '1:19239814105:ios:8489eb43f6dc8520810fc8',
    messagingSenderId: '19239814105',
    projectId: 'test-d994f',
    storageBucket: 'test-d994f.appspot.com',
    iosBundleId: 'com.example.Lucerna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPa1l3cj_hUkCZyjLXOQBmpUrNCmmhKpI',
    appId: '1:19239814105:web:147a4d364526ba03810fc8',
    messagingSenderId: '19239814105',
    projectId: 'test-d994f',
    authDomain: 'test-d994f.firebaseapp.com',
    storageBucket: 'test-d994f.appspot.com',
    measurementId: 'G-YWSVRDVWBZ',
  );
}
